const CHAPTERS = [
  {
    id: 1, title: "第1章 食欲をそそってみようか", description: "Pythonの特徴と概要", rate: 2.5,
    questions: [
      { id:"1-1", text:"Pythonについての説明として正しいものはどれですか？", options:["コンパイル型言語であり、実行前にすべてのコードをコンパイルする必要がある","インタープリタ型言語であり、コードを逐次実行できる","変数を使う前に型宣言が必須である","主にWebブラウザ内で動作するスクリプト言語である"], answer:1, explanation:"Pythonはインタープリタ型言語です。コードを1行ずつ解釈・実行するため、コンパイルなしにすぐ動作確認できます。また動的型付け言語なので型宣言も不要です。" },
      { id:"1-2", text:"Pythonのインデント（字下げ）について正しい説明はどれですか？", options:["インデントは任意であり、コードの見やすさのためだけに使われる","インデントはブロック構造を表すために文法的に必須である","インデントには必ずタブ文字を使わなければならない","インデントは2スペースでなければならない"], answer:1, explanation:"Pythonではインデントがブロック構造を表すために文法的に必須です。他の言語のように波括弧{}は使いません。PEP8では4スペースが推奨されています。" },
      { id:"1-3", text:"Pythonが広く使われている分野として正しいものはどれですか？", options:["Webブラウザの拡張機能開発専用の言語である","科学計算・データ分析・機械学習・Web開発など幅広い分野で使われる","組み込みシステムのファームウェア開発のみに使われる","モバイルアプリの開発専用の言語である"], answer:1, explanation:"Pythonは汎用プログラミング言語であり、科学計算・データ分析・機械学習・Web開発・自動化スクリプトなど非常に幅広い分野で活用されています。" },
      { id:"1-4", text:"Pythonの動的型付けについて正しい説明はどれですか？", options:["変数の型はプログラム実行中に変えることができない","変数の型は実行時に決まり、同じ変数に異なる型の値を代入できる","変数を使う前に必ず型を宣言する必要がある","すべての変数は整数型として扱われる"], answer:1, explanation:"Pythonは動的型付け言語です。変数の型は宣言時ではなく代入時に決まり、同じ変数に後から異なる型の値を代入することも可能です。" },
      { id:"1-5", text:"Pythonの特徴として正しいものはどれですか？", options:["オブジェクト指向プログラミングには対応していない","オープンソースであり、無料で使用できる","Windowsでのみ動作する","コードの行末にはセミコロン(;)が必須である"], answer:1, explanation:"Pythonはオープンソースで無料のプログラミング言語です。オブジェクト指向・手続き型・関数型など複数のパラダイムをサポートし、Windows・Mac・Linuxで動作します。" },
      { id:"1-6", text:"Pythonで1行コメントを書くための記号はどれですか？", options:["//","/* */","#","--"], answer:2, explanation:"Pythonの1行コメントは「#」で始めます。#以降の文字はすべてコメントとして無視されます。//はJavaやJavaScriptのコメント記号です。" },
      { id:"1-7", text:"Python 3でprint文を使う正しい方法はどれですか？", options:["print \"Hello\"","print(\"Hello\")","echo(\"Hello\")","console.log(\"Hello\")"], answer:1, explanation:"Python 3ではprintは関数なのでprint()のように括弧が必要です。Python 2ではprint \"Hello\"と書けましたが、Python 3では構文エラーになります。" },
      { id:"1-8", text:"Pythonのメモリ管理について正しい説明はどれですか？", options:["プログラマが手動でメモリを解放する必要がある","ガベージコレクタが不要になったオブジェクトのメモリを自動的に解放する","メモリは一切解放されない","メモリの割り当ては実行前にすべて行われる"], answer:1, explanation:"Pythonにはガベージコレクタが内蔵されており、参照カウントを使って不要になったオブジェクトを自動的にメモリから解放します。C言語のような手動管理は不要です。" },
      { id:"1-9", text:"対話モードで「import this」を実行したときの説明として正しいものはどれですか？", options:["thisモジュールをインポートしてクラスを使えるようになる","Pythonの設計哲学「The Zen of Python」が表示される","this変数が定義される","エラーが発生する"], answer:1, explanation:"「import this」を実行するとThe Zen of Pythonが表示されます。「Beautiful is better than ugly.」など、Pythonの設計哲学が記されています。" },
      { id:"1-10", text:"PythonのNoneについて正しい説明はどれですか？", options:["0と同じ値である","空文字列と同じ値である","値が存在しないことを表す特別なオブジェクトである","Falseと同じ値である"], answer:2, explanation:"NoneはPythonの特殊なオブジェクトで、値が存在しないことを表します。0・False・空文字列とは別のオブジェクトです。Noneとの比較にはis演算子を使います。" },
    ]
  },
  {
    id: 2, title: "第2章 Pythonインタープリタの使い方", description: "インタープリタの起動と対話モード", rate: 2.5,
    questions: [
      { id:"2-1", text:"Pythonの対話モードで表示される一次プロンプトはどれですか？", options:["$",">",">>>","#"], answer:2, explanation:"Pythonの対話モードでは「>>>」が一次プロンプトとして表示されます。複数行入力中は「...」が二次プロンプトとして表示されます。" },
      { id:"2-2", text:"Pythonの対話モードで複数行の文を入力しているときの二次プロンプトはどれですか？", options:[">>>","...",">>",".."], answer:1, explanation:"対話モードで複数行入力（ifブロックや関数定義など）を行うとき、続く行には「...」が表示されます。入力を確定するには空行を入力します。" },
      { id:"2-3", text:"Pythonの対話モードを終了するためのコマンドはどれですか？", options:["exit() または quit()","stop()","end()","close()"], answer:0, explanation:"対話モードを終了するにはexit()またはquit()を使います。WindowsではCtrl+Z、Unix/MacではCtrl+Dでも終了できます。" },
      { id:"2-4", text:"Pythonスクリプトファイル「hello.py」をコマンドラインから実行するコマンドはどれですか？", options:["python run hello.py","python hello.py","run hello.py","execute hello.py"], answer:1, explanation:"Pythonスクリプトは「python ファイル名」で実行します。環境によってはpython3コマンドを使います。" },
      { id:"2-5", text:"「python -c 'print(1+1)'」を実行したときの動作として正しいものはどれですか？", options:["エラーが発生する","コマンドラインから直接Pythonコードを実行して 2 を出力する","対話モードが起動する","\"1+1\" という文字列を出力する"], answer:1, explanation:"-cオプションを使うと、コマンドライン引数として渡したPythonコードを直接実行できます。" },
      { id:"2-6", text:"Pythonスクリプトの文字コードをUTF-8として宣言する正しい書き方はどれですか？", options:["# encoding: utf-8","# -*- coding: utf-8 -*-","charset utf-8","# utf-8"], answer:1, explanation:"「# -*- coding: エンコーディング名 -*-」とファイル先頭に書くことでエンコーディングを指定できます。Python 3のデフォルトはUTF-8なので通常は不要です。" },
      { id:"2-7", text:"「python script.py hello world」と実行したとき、sys.argv[1]の値はどれですか？", options:["\"python\"","\"script.py\"","\"hello\"","[\"hello\", \"world\"]"], answer:2, explanation:"sys.argv[0]はスクリプト名、sys.argv[1]以降がコマンドライン引数です。この例ではsys.argv = ['script.py', 'hello', 'world']となります。" },
      { id:"2-8", text:".pycファイルの説明として正しいものはどれですか？", options:["ソースコードの暗号化ファイル","バイトコードにコンパイルされたキャッシュファイル","実行結果を保存するログファイル","ソースコードのバックアップファイル"], answer:1, explanation:".pycファイルはPythonのソースコードをバイトコードにコンパイルしたキャッシュです。次回実行時の高速化に使われ、通常は__pycache__ディレクトリに保存されます。" },
      { id:"2-9", text:"対話モードでprint関数の使い方を調べる方法はどれですか？", options:["man print","print.help()","help(print)","?print"], answer:2, explanation:"help()関数を使うと、オブジェクトのドキュメントを対話モードで表示できます。help(print)でprint関数の説明が表示されます。" },
      { id:"2-10", text:"対話環境で直前の式の評価結果が自動的に代入される特殊変数はどれですか？", options:["_result","_","__ans__","ans"], answer:1, explanation:"対話環境では直前に評価された式の値が特殊変数「_」（アンダースコア）に自動代入されます。計算結果をすぐ次の操作に使いたいときに便利です。" },
    ]
  },
  {
    id: 3, title: "第3章 気楽な入門編", description: "数値・文字列・リストの基礎", rate: 15.0,
    questions: [
      { id:"3-1", text:"次のコードの実行結果として正しいものはどれですか？\nprint(10 // 3)", options:["3.33","3","4","3.0"], answer:1, explanation:"「//」は切り捨て除算（整数除算）演算子です。10 ÷ 3 = 3.33...を切り捨てると3になります。" },
      { id:"3-2", text:"次のコードの実行結果として正しいものはどれですか？\nprint(10 % 3)", options:["3","0","1","3.3"], answer:2, explanation:"「%」は剰余（余り）演算子です。10 ÷ 3の余りは1です。" },
      { id:"3-3", text:"次のコードの実行結果として正しいものはどれですか？\ns = \"Python\"\nprint(s[2])", options:["P","y","t","h"], answer:2, explanation:"Pythonの文字列のインデックスは0始まりです。s[0]='P', s[1]='y', s[2]='t'となります。" },
      { id:"3-4", text:"次のコードの実行結果として正しいものはどれですか？\ns = \"Hello\"\nprint(s * 2)", options:["HelloHello","Hello2","10","エラーが発生する"], answer:0, explanation:"文字列に整数を掛けると、その文字列を指定回数繰り返した文字列が返ります。" },
      { id:"3-5", text:"次のコードの実行結果として正しいものはどれですか？\ns = \"Python\"\nprint(s[1:4])", options:["Pyt","yth","ytho","ython"], answer:1, explanation:"スライスs[1:4]はインデックス1から3（4は含まない）の文字を返します。s[1]='y', s[2]='t', s[3]='h'なので\"yth\"です。" },
      { id:"3-6", text:"次のコードの実行結果として正しいものはどれですか？\nx = 2 ** 10\nprint(x)", options:["20","100","512","1024"], answer:3, explanation:"「**」はべき乗演算子です。2 ** 10は2の10乗 = 1024です。" },
      { id:"3-7", text:"次のコードの実行結果として正しいものはどれですか？\ns = \"Python\"\nprint(len(s))", options:["5","6","7","エラーが発生する"], answer:1, explanation:"len()は文字列の長さ（文字数）を返します。\"Python\"は6文字なので6が返ります。" },
      { id:"3-8", text:"次のコードの実行結果として正しいものはどれですか？\ns = \"Python\"\nprint(s[-1])", options:["P","n","o","エラーが発生する"], answer:1, explanation:"負のインデックスは末尾からのアクセスを意味します。s[-1]は最後の文字'n'を返します。" },
      { id:"3-9", text:"文字列はイミュータブルです。次のコードを実行するとどうなりますか？\ns = \"Python\"\ns[0] = \"J\"", options:["sが\"Jython\"になる","何も変化しない","TypeErrorが発生する","ValueErrorが発生する"], answer:2, explanation:"Pythonの文字列はイミュータブルなので、インデックスによる個々の文字への代入はできません。TypeErrorが発生します。" },
      { id:"3-10", text:"次のコードの実行結果として正しいものはどれですか？\nprint(\"Hello\" + \" \" + \"World\")", options:["HelloWorld","Hello World","Hello + World","エラーが発生する"], answer:1, explanation:"「+」演算子で文字列を連結できます。" },
      { id:"3-11", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [1, 2, 3]\nprint(lst[1])", options:["1","2","3","エラーが発生する"], answer:1, explanation:"リストのインデックスも0始まりです。lst[0]=1, lst[1]=2です。" },
      { id:"3-12", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [1, 2, 3, 4, 5]\nprint(lst[1:3])", options:["[1, 2]","[2, 3]","[2, 3, 4]","[1, 2, 3]"], answer:1, explanation:"リストのスライスlst[1:3]はインデックス1から2（3は含まない）の要素を返します。" },
      { id:"3-13", text:"次のコードの実行結果として正しいものはどれですか？\nx, y, z = 1, 2, 3\nprint(y)", options:["1","2","3","エラーが発生する"], answer:1, explanation:"Pythonではカンマ区切りで複数の変数に同時に代入できます（アンパック代入）。x=1, y=2, z=3となります。" },
      { id:"3-14", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [1, 2, 3]\nlst.append(4)\nprint(lst)", options:["[1, 2, 3]","[4, 1, 2, 3]","[1, 2, 3, 4]","エラーが発生する"], answer:2, explanation:"append()はリストの末尾に要素を追加します。lstに4が追加されて[1, 2, 3, 4]になります。" },
      { id:"3-15", text:"次のコードでtype(x)の実行結果として正しいものはどれですか？\nx = 3.14", options:["<class 'int'>","<class 'float'>","<class 'str'>","<class 'double'>"], answer:1, explanation:"3.14は小数点を含む数値なので浮動小数点型（float）です。Pythonにdouble型はなく、floatが倍精度浮動小数点数を表します。" },
      { id:"3-16", text:"次のコードの実行結果として正しいものはどれですか？\ns = \"hello world\"\nprint(s.upper())", options:["hello world","HELLO WORLD","Hello World","エラーが発生する"], answer:1, explanation:"upper()メソッドは文字列のすべての文字を大文字に変換します。逆にlower()は小文字に変換します。" },
      { id:"3-17", text:"次のコードの実行結果として正しいものはどれですか？\ns = \"a,b,c\"\nprint(s.split(\",\"))", options:["(\"a\", \"b\", \"c\")","[\"a\", \"b\", \"c\"]","{\"a\", \"b\", \"c\"}","\"a b c\""], answer:1, explanation:"split()メソッドは指定した区切り文字で文字列を分割し、リストを返します。" },
      { id:"3-18", text:"次のコードの実行結果として正しいものはどれですか？\nprint(\"Python\" in \"I love Python\")", options:["\"Python\"","True","False","エラーが発生する"], answer:1, explanation:"in演算子はシーケンスに要素が含まれているか調べます。\"Python\"は\"I love Python\"に含まれているのでTrueが返ります。" },
      { id:"3-19", text:"次のコードの実行結果として正しいものはどれですか？\ns = \"  hello  \"\nprint(s.strip())", options:["\"  hello  \"","\"hello\"","\"hello  \"","\"  hello\""], answer:1, explanation:"strip()メソッドは文字列の先頭と末尾の空白（スペース・タブ・改行）を取り除きます。" },
      { id:"3-20", text:"次のコードの実行結果として正しいものはどれですか？\nprint(\"-\".join([\"a\", \"b\", \"c\"]))", options:["[\"a\", \"b\", \"c\"]","a-b-c","a,b,c","エラーが発生する"], answer:1, explanation:"join()メソッドは区切り文字でリストの要素を結合した文字列を返します。\"-\".join([\"a\",\"b\",\"c\"])は\"a-b-c\"になります。" },
      { id:"3-21", text:"次のコードの実行結果として正しいものはどれですか？\nprint(\"hello\".replace(\"l\", \"L\"))", options:["heLLo","heLlo","HELLO","helloL"], answer:0, explanation:"replace(old, new)はoldをnewにすべて置換します。\"hello\"の\"l\"をすべて\"L\"に置換すると\"heLLo\"になります。heLloは1文字しか置換されていないので誤りです。" },
      { id:"3-22", text:"次のコードの実行結果として正しいものはどれですか？\nprint(\"Python\".startswith(\"Py\"))", options:["\"Py\"","True","False","エラーが発生する"], answer:1, explanation:"startswith()は文字列が指定した文字列で始まる場合にTrueを返します。\"Python\"は\"Py\"で始まるのでTrueです。" },
      { id:"3-23", text:"次のコードの実行結果として正しいものはどれですか？\nprint(bool(\"\"))", options:["True","False","None","エラーが発生する"], answer:1, explanation:"空文字列はFalsy（偽）な値です。bool(\"\")はFalseになります。空でない文字列はすべてTruthyです。" },
      { id:"3-24", text:"Pythonで整数を16進数の文字列として取得する関数はどれですか？", options:["int()","hex()","str()","oct()"], answer:1, explanation:"hex()は整数を16進数の文字列（'0x'プレフィックス付き）に変換します。例：hex(255)は'0xff'を返します。" },
      { id:"3-25", text:"次のコードの実行結果として正しいものはどれですか？\nprint(str(42))", options:["42","\"42\"","42.0","エラーが発生する"], answer:0, explanation:"str()は値を文字列に変換します。print()で出力すると\"42\"（クォートなし）と表示されます。" },
    ]
  },
  {
    id: 4, title: "第4章 制御構造ツール", description: "if・for・while・関数・lambda", rate: 22.5,
    questions: [
      { id:"4-1", text:"次のコードの実行結果として正しいものはどれですか？\nfor i in range(3):\n    print(i)", options:["1\n2\n3","0\n1\n2","0\n1\n2\n3","1\n2\n3\n4"], answer:1, explanation:"range(3)は0, 1, 2の3つの値を生成します。range(n)は0からn-1までの整数を返します。" },
      { id:"4-2", text:"次のコードを実行後のiの値として正しいものはどれですか？\ni = 0\nwhile i < 3:\n    i += 1\nprint(i)", options:["0","2","3","4"], answer:2, explanation:"ループはiが3未満の間繰り返されます。iが3になるとループを抜けるため、print(i)では3が出力されます。" },
      { id:"4-3", text:"break文の説明として正しいものはどれですか？", options:["現在のイテレーションをスキップして次に進む","最も内側のループを抜ける","プログラム全体を終了させる","関数から値を返す"], answer:1, explanation:"break文は最も内側のループ（forまたはwhile）を即座に終了させます。外側のループは継続されます。" },
      { id:"4-4", text:"continue文の説明として正しいものはどれですか？", options:["ループを完全に終了する","プログラムを一時停止する","現在のイテレーションをスキップして次のイテレーションに進む","例外を発生させる"], answer:2, explanation:"continue文は現在のループのイテレーションの残りをスキップし、次のイテレーションを開始します。" },
      { id:"4-5", text:"次のコードの実行結果として正しいものはどれですか？\ndef greet(name=\"World\"):\n    print(f\"Hello, {name}!\")\n\ngreet()", options:["Hello, !","Hello, name!","Hello, World!","エラーが発生する"], answer:2, explanation:"引数nameにはデフォルト値\"World\"が設定されています。引数なしでgreet()を呼ぶとデフォルト値が使われ\"Hello, World!\"が出力されます。" },
      { id:"4-6", text:"*argsを使った関数定義について正しい説明はどれですか？", options:["任意の数のキーワード引数を辞書として受け取る","任意の数の位置引数をタプルとして受け取る","任意の数の位置引数をリストとして受け取る","引数にデフォルト値を設定する"], answer:1, explanation:"*argsを使うと任意の数の位置引数をタプルとして受け取れます。キーワード引数を受け取るには**kwargsを使います。" },
      { id:"4-7", text:"次のコードの実行結果として正しいものはどれですか？\nx = 10\nif x > 5:\n    print(\"A\")\nelif x > 8:\n    print(\"B\")\nelse:\n    print(\"C\")", options:["A","B","A\nB","C"], answer:0, explanation:"if文は上から順に評価します。x=10はx>5を満たすため\"A\"が出力され、elifとelseは評価されません。" },
      { id:"4-8", text:"pass文の説明として正しいものはどれですか？", options:["関数の実行を終了させる","ループを終了させる","何もしない文で、文法上必要な場所に使う","例外を無視する"], answer:2, explanation:"pass文は何も実行しない文です。空のクラス・関数定義など、文法的に文が必要だが処理が不要な場合に使います。" },
      { id:"4-9", text:"lambda（ラムダ）関数の説明として正しいものはどれですか？", options:["複数の式を含めることができる","defと同様に名前を付けることができる","単一の式を評価して返す無名関数である","defキーワードと併用して定義する"], answer:2, explanation:"lambda式は「lambda 引数: 式」の形で書く単一式の無名関数です。複数の文は書けません。" },
      { id:"4-10", text:"次のコードの実行結果として正しいものはどれですか？\nresult = list(range(1, 10, 2))\nprint(result)", options:["[1, 2, 3, 4, 5, 6, 7, 8, 9]","[1, 3, 5, 7, 9]","[2, 4, 6, 8]","[1, 3, 5, 7]"], answer:1, explanation:"range(start, stop, step)はstartからstop未満までstep刻みで値を生成します。range(1,10,2)は1,3,5,7,9を生成します。" },
      { id:"4-11", text:"次のコードの実行結果として正しいものはどれですか？\nfor i in range(5):\n    if i == 3:\n        break\n    print(i)", options:["0\n1\n2\n3","0\n1\n2","3\n4","0\n1\n2\n3\n4"], answer:1, explanation:"i=0,1,2のときprint(i)が実行されます。i=3になるとbreakでループを抜けるため3は出力されません。" },
      { id:"4-12", text:"次のコードの実行結果として正しいものはどれですか？\nfor i in range(5):\n    if i == 3:\n        continue\n    print(i)", options:["0\n1\n2\n3\n4","0\n1\n2\n4","3","0\n1\n2"], answer:1, explanation:"continueはそのイテレーションをスキップします。i=3のときだけprint(i)がスキップされ、0,1,2,4が出力されます。" },
      { id:"4-13", text:"次のコードの実行結果として正しいものはどれですか？\ndef add(a, b):\n    return a + b\n\nresult = add(3, 4)\nprint(result)", options:["a + b","7","34","エラーが発生する"], answer:1, explanation:"関数addは引数aとbを受け取りその合計を返します。add(3,4)は3+4=7を返します。" },
      { id:"4-14", text:"**kwargsを使った関数定義について正しい説明はどれですか？", options:["任意の数の位置引数をタプルとして受け取る","任意の数のキーワード引数を辞書として受け取る","引数の数を固定する","デフォルト引数を設定する"], answer:1, explanation:"**kwargsを使うと任意の数のキーワード引数を辞書として受け取れます。func(a=1, b=2)と呼ぶとkwargsは{'a':1,'b':2}になります。" },
      { id:"4-15", text:"次のlambda式の実行結果として正しいものはどれですか？\nsquare = lambda x: x ** 2\nprint(square(5))", options:["25","10","lambda","エラーが発生する"], answer:0, explanation:"lambda x: x**2は引数xを受け取りxの2乗を返す無名関数です。square(5)は5**2=25を返します。" },
      { id:"4-16", text:"for文にelse節を付けた場合の動作として正しい説明はどれですか？", options:["ループが1回も実行されなかった場合にelse節が実行される","ループがbreakで終了した場合にelse節が実行される","ループがbreakなく正常に終了した場合にelse節が実行される","else節はfor文では使用できない"], answer:2, explanation:"for文のelse節はループがbreakによって中断されることなく正常終了した場合に実行されます。" },
      { id:"4-17", text:"次のコードの実行結果として正しいものはどれですか？\ndef func(a, b=10):\n    return a + b\n\nprint(func(5))", options:["5","10","15","エラーが発生する"], answer:2, explanation:"bにはデフォルト値10が設定されています。func(5)はa=5,b=10（デフォルト）で呼ばれるため5+10=15が返ります。" },
      { id:"4-18", text:"次のコードの実行結果として正しいものはどれですか？\ndef func(*args):\n    return sum(args)\n\nprint(func(1, 2, 3, 4))", options:["(1, 2, 3, 4)","10","[1, 2, 3, 4]","エラーが発生する"], answer:1, explanation:"*argsでキャプチャされた引数はタプルになります。sum((1,2,3,4))=10が返ります。" },
      { id:"4-19", text:"Pythonのグローバル変数を関数内で変更するために必要なキーワードはどれですか？", options:["static","global","extern","var"], answer:1, explanation:"関数内でグローバル変数に代入するにはglobalキーワードで宣言する必要があります。宣言なしで代入すると新しいローカル変数が作成されます。" },
      { id:"4-20", text:"次のコードの実行結果として正しいものはどれですか？\nresult = list(map(lambda x: x*2, [1, 2, 3]))\nprint(result)", options:["[1, 2, 3]","[2, 4, 6]","(2, 4, 6)","エラーが発生する"], answer:1, explanation:"map()は関数を各要素に適用します。lambda x: x*2を[1,2,3]に適用すると[2,4,6]になります。" },
      { id:"4-21", text:"次のコードの実行結果として正しいものはどれですか？\nresult = list(filter(lambda x: x > 2, [1, 2, 3, 4]))\nprint(result)", options:["[1, 2]","[3, 4]","[1, 2, 3, 4]","エラーが発生する"], answer:1, explanation:"filter()は条件がTrueの要素だけを残します。x>2を満たす要素は3と4なので[3,4]になります。" },
      { id:"4-22", text:"次のコードの実行結果として正しいものはどれですか？\nprint(any([False, False, True, False]))", options:["False","True","None","エラーが発生する"], answer:1, explanation:"any()はイテラブルの要素に1つでもTruthyなものがあればTrueを返します。1つでもTrueがあるのでTrueになります。" },
      { id:"4-23", text:"次のコードの実行結果として正しいものはどれですか？\nprint(all([True, True, False, True]))", options:["False","True","None","エラーが発生する"], answer:0, explanation:"all()はすべての要素がTruthyであればTrueを返します。Falseが含まれているためFalseになります。" },
      { id:"4-24", text:"Pythonの三項演算子（条件式）の正しい書き方はどれですか？", options:["x if cond else y","cond ? x : y","x when cond else y","if cond then x else y"], answer:0, explanation:"Pythonの条件式（三項演算子）は「真の値 if 条件 else 偽の値」の形で書きます。" },
      { id:"4-25", text:"次のコードの実行結果として正しいものはどれですか？\nfor a, b in zip([1,2,3], [\"a\",\"b\",\"c\"]):\n    print(a, b)", options:["1 2 3\na b c","1 a\n2 b\n3 c","(1,'a') (2,'b') (3,'c')","エラーが発生する"], answer:1, explanation:"zip()は複数のイテラブルを同時にループします。各イテレーションで対応する要素がタプルとしてアンパックされます。" },
    ]
  },
  {
    id: 5, title: "第5章 データ構造", description: "リスト・タプル・辞書・集合・内包表記", rate: 17.5,
    questions: [
      { id:"5-1", text:"リストの末尾に要素を1つ追加するメソッドはどれですか？", options:["add()","insert()","append()","push()"], answer:2, explanation:"append()はリストの末尾に要素を1つ追加します。insert(i,x)は位置を指定して挿入、extend()はリストを結合します。" },
      { id:"5-2", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [3, 1, 4, 1, 5]\nlst.sort()\nprint(lst)", options:["[3, 1, 4, 1, 5]","[1, 1, 3, 4, 5]","[5, 4, 3, 1, 1]","エラーが発生する"], answer:1, explanation:"sort()はリストを昇順に並び替えます（元のリストを変更します）。降順にするにはsort(reverse=True)を使います。" },
      { id:"5-3", text:"タプル（tuple）とリスト（list）の違いとして正しいものはどれですか？", options:["タプルはリストより多くの要素を格納できる","タプルはイミュータブル（変更不可）である","タプルは数値のみを格納できる","タプルは辞書のキーとして使えない"], answer:1, explanation:"タプルはイミュータブル（変更不可）なシーケンス型です。一方リストはミュータブル（変更可能）です。タプルは辞書のキーとして使用できます。" },
      { id:"5-4", text:"次のコードの実行結果として正しいものはどれですか？\nd = {\"a\": 1, \"b\": 2}\nprint(d[\"b\"])", options:["\"b\"","1","2","{\"b\": 2}"], answer:2, explanation:"辞書はキーを使って値にアクセスします。d[\"b\"]はキー\"b\"に対応する値2を返します。" },
      { id:"5-5", text:"次のリスト内包表記の実行結果として正しいものはどれですか？\nresult = [x ** 2 for x in range(4)]\nprint(result)", options:["[0, 1, 2, 3]","[1, 4, 9, 16]","[0, 1, 4, 9]","[0, 2, 4, 6]"], answer:2, explanation:"range(4)は0,1,2,3を生成します。各要素を2乗すると0,1,4,9となり[0,1,4,9]になります。" },
      { id:"5-6", text:"集合（set）について正しい説明はどれですか？", options:["重複する要素を持つことができる","順序を保持し、インデックスでアクセスできる","重複する要素を持たず、順序は保証されない","キーと値のペアを格納する"], answer:2, explanation:"集合（set）は重複のない要素の集まりです。順序は保証されないためインデックスアクセスはできません。" },
      { id:"5-7", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [1, 2, 3, 4, 5]\ndel lst[1:3]\nprint(lst)", options:["[1, 4, 5]","[2, 3]","[1, 2, 4, 5]","[1, 2, 3]"], answer:0, explanation:"del lst[1:3]はインデックス1から2（3は含まない）の要素、つまり2と3を削除します。結果は[1,4,5]です。" },
      { id:"5-8", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [1, 2, 3]\nlst.extend([4, 5])\nprint(lst)", options:["[1, 2, 3, [4, 5]]","[1, 2, 3, 4, 5]","[[1, 2, 3], [4, 5]]","エラーが発生する"], answer:1, explanation:"extend()は引数のイテラブルの各要素をリストに追加します。append([4,5])だと[1,2,3,[4,5]]になります。" },
      { id:"5-9", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [3, 1, 4, 1, 5, 9]\nprint(lst.count(1))", options:["1","2","3","エラーが発生する"], answer:1, explanation:"count()はリスト内の指定した値の出現回数を返します。[3,1,4,1,5,9]の中に1は2回あるので2が返ります。" },
      { id:"5-10", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [1, 2, 3, 4, 5]\nprint(lst.pop())", options:["1","5","[1, 2, 3, 4]","エラーが発生する"], answer:1, explanation:"pop()は引数なしの場合、リストの末尾の要素を削除してその値を返します。" },
      { id:"5-11", text:"辞書のすべてのキーを取得するメソッドはどれですか？", options:["d.keys()","d.key()","d.getkeys()","d.allkeys()"], answer:0, explanation:"辞書のキー一覧はkeys()で取得します。values()で値一覧、items()でキーと値のペア一覧が取得できます。" },
      { id:"5-12", text:"次のコードの実行結果として正しいものはどれですか？\nresult = [x for x in range(10) if x % 2 == 0]\nprint(result)", options:["[1, 3, 5, 7, 9]","[0, 2, 4, 6, 8]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","[2, 4, 6, 8, 10]"], answer:1, explanation:"リスト内包表記に条件を付けると、条件を満たす要素だけでリストを作れます。x%2==0は偶数の条件なので[0,2,4,6,8]になります。" },
      { id:"5-13", text:"次のコードの実行結果として正しいものはどれですか？\ns = {1, 2, 3} | {3, 4, 5}\nprint(s)", options:["{1, 2, 3, 4, 5}","{3}","{1, 2, 4, 5}","エラーが発生する"], answer:0, explanation:"集合の「|」は和集合演算子です。{1,2,3}と{3,4,5}の和集合は{1,2,3,4,5}です（重複する3は1つにまとめられます）。" },
      { id:"5-14", text:"次のコードの実行結果として正しいものはどれですか？\nfor i, v in enumerate([\"a\", \"b\", \"c\"]):\n    print(i, v)", options:["a b c","0 a\n1 b\n2 c","1 a\n2 b\n3 c","エラーが発生する"], answer:1, explanation:"enumerate()はイテラブルにインデックスと値のペアを返します。デフォルトはインデックス0始まりです。" },
      { id:"5-15", text:"次のコードの実行結果として正しいものはどれですか？\nd = {\"x\": 10}\nprint(d.get(\"y\", 0))", options:["10","\"y\"","0","KeyErrorが発生する"], answer:2, explanation:"dict.get(key, default)はキーが存在すればその値を、存在しなければデフォルト値を返します。\"y\"キーは存在しないので0が返ります。" },
      { id:"5-16", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [5, 3, 1, 4, 2]\nprint(sorted(lst))", options:["[5, 3, 1, 4, 2]","[1, 2, 3, 4, 5]","[5, 4, 3, 2, 1]","エラーが発生する"], answer:1, explanation:"sorted()は元のリストを変更せずに、ソートされた新しいリストを返します。lst.sort()は元のリストを変更します。" },
      { id:"5-17", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [1, 2, 3]\nlst.insert(1, 10)\nprint(lst)", options:["[1, 2, 3, 10]","[1, 10, 2, 3]","[10, 1, 2, 3]","エラーが発生する"], answer:1, explanation:"insert(i, x)はインデックスiの位置にxを挿入します。insert(1,10)はインデックス1に10を挿入するため[1,10,2,3]になります。" },
      { id:"5-18", text:"次のコードの実行結果として正しいものはどれですか？\ns1 = {1, 2, 3}\ns2 = {2, 3, 4}\nprint(s1 & s2)", options:["{1, 2, 3, 4}","{2, 3}","{1, 4}","エラーが発生する"], answer:1, explanation:"集合の「&」は積集合（共通部分）演算子です。{1,2,3}と{2,3,4}の積集合は{2,3}です。" },
      { id:"5-19", text:"辞書の内包表記として正しいものはどれですか？", options:["{x: x**2 for x in range(3)}","[x: x**2 for x in range(3)]","(x: x**2 for x in range(3))","dict(x: x**2 for x in range(3))"], answer:0, explanation:"辞書内包表記は「{キー: 値 for 変数 in イテラブル}」の形で書きます。{x: x**2 for x in range(3)}は{0:0, 1:1, 2:4}になります。" },
      { id:"5-20", text:"次のコードの実行結果として正しいものはどれですか？\nlst = [1, 2, 2, 3, 3, 3]\nprint(len(set(lst)))", options:["6","3","1","エラーが発生する"], answer:1, explanation:"set()は重複を除去します。[1,2,2,3,3,3]のsetは{1,2,3}で3要素です。len({1,2,3})=3が返ります。" },
    ]
  },
  {
    id: 6, title: "第6章 モジュール", description: "import文とモジュールの使い方", rate: 5.0,
    questions: [
      { id:"6-1", text:"「import math」した後、16の平方根を計算する正しい書き方はどれですか？", options:["math(sqrt(16))","sqrt(16)","math.sqrt(16)","import.math.sqrt(16)"], answer:2, explanation:"import文でモジュールをインポートした場合、「モジュール名.関数名()」でアクセスします。math.sqrt(16)は4.0を返します。" },
      { id:"6-2", text:"「from os import path」を実行した後、パスを結合する正しい書き方はどれですか？", options:["os.path.join(\"a\", \"b\")","path.join(\"a\", \"b\")","join(\"a\", \"b\")","from.path.join(\"a\", \"b\")"], answer:1, explanation:"「from モジュール名 import 名前」でインポートすると、モジュール名なしで直接使えます。" },
      { id:"6-3", text:"モジュールを別名（エイリアス）でインポートする正しい書き方はどれですか？", options:["import numpy alias np","import numpy as np","from numpy import as np","numpy import np"], answer:1, explanation:"「import モジュール名 as 別名」でモジュールに別名をつけてインポートできます。numpyはnp、pandasはpdが慣例です。" },
      { id:"6-4", text:"スクリプトファイルを直接実行した場合、__name__の値はどれになりますか？", options:["__module__","None","__main__","ファイル名（拡張子なし）"], answer:2, explanation:"スクリプトを直接実行すると__name__は\"__main__\"になります。インポートされた場合はモジュール名になります。" },
      { id:"6-5", text:"モジュール内で定義された名前の一覧を調べる組み込み関数はどれですか？", options:["list()","dir()","help()","vars()"], answer:1, explanation:"dir()はオブジェクトや現在のスコープ内の名前一覧を返します。dir(math)でmathモジュールの名前をリストで確認できます。" },
      { id:"6-6", text:"「from math import *」について正しい説明はどれですか？", options:["mathモジュールのアンダースコアで始まるものだけをインポートする","mathモジュールのすべての公開名を現在の名前空間にインポートする","mathモジュールを上書きする","エラーが発生する"], answer:1, explanation:"「from モジュール名 import *」でモジュールの全公開名がインポートされます。名前衝突の危険があるため推奨されません。" },
      { id:"6-7", text:"Pythonでパッケージを示すためにディレクトリ内に置くファイルはどれですか？", options:["package.py","__init__.py","main.py","__package__.py"], answer:1, explanation:"Pythonのパッケージはディレクトリに__init__.pyを置くことで識別されます。" },
      { id:"6-8", text:"次のコードの実行結果として正しいものはどれですか？\nimport math\nprint(math.pi)", options:["3","3.14","3.141592653589793","エラーが発生する"], answer:2, explanation:"math.piは円周率πの値を表す定数です。Pythonでは3.141592653589793として定義されています。" },
      { id:"6-9", text:"Pythonのモジュール検索パスを格納しているのはどれですか？", options:["os.path","sys.path","import.path","module.path"], answer:1, explanation:"sys.pathはPythonがモジュールを検索するディレクトリのリストです。このリストにパスを追加するとそのディレクトリのモジュールもインポートできます。" },
      { id:"6-10", text:"「from math import sqrt, pi」について正しい説明はどれですか？", options:["sqrtとpiだけをインポートし、直接使える","mathモジュール全体をsqrtとpiという名前でインポートする","sqrtとpiをまとめてmathという名前でインポートする","エラーが発生する"], answer:0, explanation:"「from モジュール名 import 名前1, 名前2」で複数の名前を直接インポートできます。sqrt(16)やpiと直接書けます。" },
    ]
  },
  {
    id: 7, title: "第7章 入出力", description: "print・フォーマット・ファイル操作", rate: 2.5,
    questions: [
      { id:"7-1", text:"次のコードの実行結果として正しいものはどれですか？\nname = \"Python\"\nversion = 3.9\nprint(f\"{name} {version:.1f}\")", options:["Python 3.9","Python version","name version","エラーが発生する"], answer:0, explanation:"f文字列では{変数名}で変数を埋め込めます。{version:.1f}は小数点1桁の浮動小数点形式を指定します。" },
      { id:"7-2", text:"print()関数でカンマ区切りの代わりに「-」でつなげて出力するための正しい書き方はどれですか？", options:["print(\"a\", \"b\", \"c\", sep=\"-\")","print(\"a\", \"b\", \"c\", join=\"-\")","print(\"a\" - \"b\" - \"c\")","print(\"a\", \"b\", \"c\", delimiter=\"-\")"], answer:0, explanation:"print()のsep引数で区切り文字を指定できます。デフォルトはスペースです。sep=\"-\"にすると\"a-b-c\"が出力されます。" },
      { id:"7-3", text:"ファイルをテキストモードで読み込む正しい書き方はどれですか？", options:["f = open(\"file.txt\", \"w\")","f = open(\"file.txt\", \"r\")","f = open(\"file.txt\", \"a\")","f = open(\"file.txt\", \"rb\")"], answer:1, explanation:"open()の第2引数はモードです。\"r\"は読み取り専用（デフォルト）、\"w\"は書き込み（上書き）、\"a\"は追記、\"b\"はバイナリモードです。" },
      { id:"7-4", text:"ファイル操作にwith文を使う利点として正しい説明はどれですか？", options:["ファイルを高速に読み込める","例外が発生してもファイルが自動的にクローズされる","ファイルを圧縮して保存できる","ファイルの書き込み権限を自動的に取得できる"], answer:1, explanation:"with文（コンテキストマネージャ）を使うと、ブロックを抜けた際（例外が発生した場合も含む）にファイルが自動的にクローズされます。" },
      { id:"7-5", text:"次のコードの実行結果として正しいものはどれですか？\nprint(\"{:>10}\".format(\"hello\"))", options:["hello     ","     hello","hello","エラーが発生する"], answer:1, explanation:"{:>10}は幅10文字で右寄せを指定します。\"hello\"は5文字なので左に5つのスペースが付いた\"     hello\"が出力されます。" },
      { id:"7-6", text:"print()関数のend引数のデフォルト値はどれですか？", options:["\"\"（空文字）","\" \"（スペース）","\"\\n\"（改行）","None"], answer:2, explanation:"print()のend引数のデフォルトは\"\\n\"（改行）です。print(\"hello\", end=\"\")とすると改行なしで出力できます。" },
      { id:"7-7", text:"ファイルの全行をリストとして読み込むメソッドはどれですか？", options:["f.read()","f.readlines()","f.readline()","f.readall()"], answer:1, explanation:"readlines()はファイルの全行を文字列のリストとして返します。readline()は1行だけ、read()は全体を1つの文字列として読み込みます。" },
      { id:"7-8", text:"次のf文字列の実行結果として正しいものはどれですか？\nx = 255\nprint(f\"{x:08b}\")", options:["255","11111111","00000000","エラーが発生する"], answer:1, explanation:"{x:08b}は2進数（b）を幅8文字でゼロ埋め（08）で表示します。255を2進数にすると11111111（8桁）になります。" },
    ]
  },
  {
    id: 8, title: "第8章 エラーと例外", description: "try・except・raise・例外の種類", rate: 10.0,
    questions: [
      { id:"8-1", text:"次のコードを実行したとき発生する例外はどれですか？\nx = int(\"abc\")", options:["TypeError","ValueError","SyntaxError","NameError"], answer:1, explanation:"int()に数値に変換できない文字列を渡すとValueErrorが発生します。" },
      { id:"8-2", text:"finallyブロックについて正しい説明はどれですか？", options:["例外が発生した場合のみ実行される","例外が発生しなかった場合のみ実行される","例外の有無にかかわらず常に実行される","exceptブロックの中では実行されない"], answer:2, explanation:"finallyブロックは例外が発生したかどうかにかかわらず、必ず実行されます。後処理の保証に使われます。" },
      { id:"8-3", text:"次のコードの実行結果として正しいものはどれですか？\ntry:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print(\"エラー\")\nelse:\n    print(\"正常\")", options:["正常","エラー","エラー\n正常","何も出力されない"], answer:1, explanation:"1/0はZeroDivisionErrorを発生させます。exceptブロックが実行されて\"エラー\"が出力されます。else節は例外がなかった場合のみ実行されます。" },
      { id:"8-4", text:"独自の例外クラスを定義するとき継承すべきクラスはどれですか？", options:["Error","Exception","RuntimeErrorのみ","Pythonでは独自の例外クラスを定義できない"], answer:1, explanation:"独自例外クラスはExceptionクラス（またはそのサブクラス）を継承して定義します。" },
      { id:"8-5", text:"次のコードを実行したとき発生する例外はどれですか？\nlst = [1, 2, 3]\nprint(lst[5])", options:["ValueError","KeyError","IndexError","TypeError"], answer:2, explanation:"リストの存在しないインデックスにアクセスするとIndexErrorが発生します。" },
      { id:"8-6", text:"raise文の説明として正しいものはどれですか？", options:["例外を捕捉する","例外を意図的に発生させる","例外を無視する","プログラムを終了させる"], answer:1, explanation:"raise文は例外を意図的に発生させます。「raise ValueError('メッセージ')」のように使います。" },
      { id:"8-7", text:"次のコードを実行したとき発生する例外はどれですか？\nd = {\"a\": 1}\nprint(d[\"b\"])", options:["IndexError","ValueError","KeyError","AttributeError"], answer:2, explanation:"辞書に存在しないキーでアクセスするとKeyErrorが発生します。エラーを回避するにはd.get(\"b\")を使います。" },
      { id:"8-8", text:"複数の例外をまとめて1つのexcept節で処理する正しい書き方はどれですか？", options:["except ValueError, TypeError:","except (ValueError, TypeError):","except ValueError or TypeError:","except ValueError | TypeError:"], answer:1, explanation:"複数の例外をまとめて処理するには「except (例外1, 例外2):」のようにタプルで指定します。" },
      { id:"8-9", text:"次のコードを実行したとき発生する例外はどれですか？\nprint(undefined_variable)", options:["ValueError","TypeError","NameError","AttributeError"], answer:2, explanation:"定義されていない変数を参照するとNameErrorが発生します。" },
      { id:"8-10", text:"次のコードを実行したとき発生する例外はどれですか？\nresult = \"hello\" + 5", options:["ValueError","TypeError","SyntaxError","NameError"], answer:1, explanation:"文字列と整数を+演算子で結合しようとするとTypeErrorが発生します。str(5)で変換してから結合する必要があります。" },
      { id:"8-11", text:"例外情報を変数に格納して利用する正しい書き方はどれですか？", options:["except Exception, e:","except Exception as e:","except (Exception, e):","except e = Exception:"], answer:1, explanation:"「except 例外クラス as 変数名:」で例外オブジェクトを変数に格納できます。print(e)でエラーメッセージを表示できます。" },
      { id:"8-12", text:"次のコードを実行したとき発生する例外はどれですか？\nobj = None\nprint(obj.upper())", options:["TypeError","AttributeError","NoneError","NameError"], answer:1, explanation:"NoneはNoneType型のオブジェクトであり、upper()メソッドを持ちません。存在しない属性やメソッドにアクセスしようとするとAttributeErrorが発生します。" },
      { id:"8-13", text:"assert文の説明として正しいものはどれですか？", options:["例外を捕捉する","条件が偽のときAssertionErrorを発生させる","プログラムを終了させる","例外を無視する"], answer:1, explanation:"assert文は条件が偽（False）のときAssertionErrorを発生させます。デバッグや前提条件のチェックに使います。" },
      { id:"8-14", text:"次のコードを実行したとき発生する例外はどれですか？\nx = 1\nx()", options:["NameError","AttributeError","TypeError","SyntaxError"], answer:2, explanation:"整数などの呼び出し不可能なオブジェクトを関数のように呼び出そうとするとTypeErrorが発生します。" },
      { id:"8-15", text:"SyntaxErrorが発生するのはどのタイミングですか？", options:["実行時","コンパイル（構文解析）時","インポート時のみ","プログラム終了時"], answer:1, explanation:"SyntaxErrorはPythonがコードを解析（パース）する際に構文の誤りを検出したときに発生します。実行前に検出されます。" },
    ]
  },
  {
    id: 9, title: "第9章 クラス", description: "クラス定義・継承・インスタンス", rate: 5.0,
    questions: [
      { id:"9-1", text:"クラスのインスタンス生成時に自動的に呼び出される特殊メソッドはどれですか？", options:["__start__()","__new__()","__init__()","__create__()"], answer:2, explanation:"__init__()はインスタンス初期化メソッドです。インスタンス生成時に自動的に呼ばれ、属性の初期化などに使います。なお__new__()はインスタンスを実際に生成するメソッドで、__init__()はその後に初期化を行います。通常オーバーライドするのは__init__()です。" },
      { id:"9-2", text:"次のコードの実行結果として正しいものはどれですか？\nclass Animal:\n    def speak(self):\n        return \"...\"\n\nclass Dog(Animal):\n    def speak(self):\n        return \"Woof!\"\n\nd = Dog()\nprint(d.speak())", options:["...","Woof!","エラーが発生する","None"], answer:1, explanation:"DogクラスはAnimalクラスを継承していますが、speak()メソッドをオーバーライドしています。d.speak()はDogクラスのspeak()が呼ばれます。" },
      { id:"9-3", text:"インスタンスメソッドの第1引数として慣習的に使われる名前はどれですか？", options:["this","me","self","cls"], answer:2, explanation:"Pythonのインスタンスメソッドの第1引数にはインスタンス自身が渡されます。慣習的にselfと命名します。クラスメソッドではclsを使います。" },
      { id:"9-4", text:"次のコードのCounter.countの出力として正しいものはどれですか？\nclass Counter:\n    count = 0\n    def __init__(self):\n        Counter.count += 1\n\na = Counter()\nb = Counter()\nprint(Counter.count)", options:["0","1","2","エラーが発生する"], answer:2, explanation:"countはクラス変数です。インスタンスを生成するたびに__init__でCounter.countが1増えます。2つのインスタンスを生成したのでcountは2です。" },
      { id:"9-5", text:"親クラスのメソッドを子クラスから呼び出すための正しい書き方はどれですか？", options:["parent.method()","super().method()","base.method()","inherited.method()"], answer:1, explanation:"super()を使うと親クラス（スーパークラス）にアクセスできます。子クラスの__init__で親の__init__を呼ぶ場合はsuper().__init__()とします。" },
      { id:"9-6", text:"isinstance(obj, ClassName)の説明として正しいものはどれですか？", options:["objのクラス名を文字列で返す","objがClassNameまたはそのサブクラスのインスタンスであればTrueを返す","ClassNameのすべてのインスタンスを返す","objの属性一覧を返す"], answer:1, explanation:"isinstance(obj, ClassName)はobjがClassNameまたはそのサブクラスのインスタンスであればTrueを返します。" },
      { id:"9-7", text:"次のコードの実行結果として正しいものはどれですか？\nclass MyClass:\n    def __str__(self):\n        return \"MyClass instance\"\n\nobj = MyClass()\nprint(obj)", options:["<MyClass object>","MyClass instance","None","エラーが発生する"], answer:1, explanation:"__str__()はオブジェクトの文字列表現を返す特殊メソッドです。print()やstr()で使われます。" },
      { id:"9-8", text:"Pythonのクラスについて正しいものはどれですか？", options:["1つの親クラスしか持てない（単一継承のみ）","複数の親クラスを持つ多重継承がサポートされている","クラスのインスタンスは一度作ると属性を追加できない","クラス定義内では関数（メソッド）を定義できない"], answer:1, explanation:"Pythonは多重継承をサポートしています。「class Dog(Animal, Mammal):」のように複数の親クラスを指定できます。" },
      { id:"9-9", text:"クラス変数とインスタンス変数の違いとして正しいものはどれですか？", options:["クラス変数はすべてのインスタンスで共有され、インスタンス変数は各インスタンス固有","インスタンス変数はすべてのインスタンスで共有される","クラス変数はコンストラクタ内で定義する","インスタンス変数はクラス直下に定義する"], answer:0, explanation:"クラス変数はすべてのインスタンスで共有されます。インスタンス変数はself.変数名で定義され、各インスタンスが独自の値を持ちます。" },
      { id:"9-10", text:"次のコードの実行結果として正しいものはどれですか？\nclass Calc:\n    def __add__(self, other):\n        return \"added\"\n\nc = Calc()\nprint(c + c)", options:["エラーが発生する","added","None","0"], answer:1, explanation:"__add__()は「+」演算子をオーバーロードする特殊メソッドです。c + cを実行するとc.__add__(c)が呼ばれ\"added\"が返ります。" },
    ]
  },
  {
    id: 10, title: "第10章 標準ライブラリめぐり", description: "os・math・datetime・random", rate: 10.0,
    questions: [
      { id:"10-1", text:"os.getcwd()の説明として正しいものはどれですか？", options:["ファイルを削除する","現在の作業ディレクトリのパスを返す","新しいディレクトリを作成する","ディレクトリの中のファイル一覧を返す"], answer:1, explanation:"os.getcwd()はCurrent Working Directory（現在の作業ディレクトリ）のパスを文字列で返します。" },
      { id:"10-2", text:"random.choice([1, 2, 3, 4, 5])の説明として正しいものはどれですか？", options:["リストを無作為に並び替える","リストから1つの要素をランダムに選んで返す","1から5のランダムな整数を生成する","リストの先頭要素を返す"], answer:1, explanation:"random.choice(seq)はシーケンスからランダムに1つの要素を選んで返します。" },
      { id:"10-3", text:"math.floor(3.7)の実行結果として正しいものはどれですか？", options:["4","3","3.7","エラーが発生する"], answer:1, explanation:"math.floor()は引数以下の最大の整数（切り捨て）を返します。3.7を切り捨てると3になります。" },
      { id:"10-4", text:"datetimeモジュールの説明として正しいものはどれですか？", options:["ファイルの日時情報のみを扱う","日付と時刻の操作に使われるモジュールである","ネットワークの通信時刻を取得する専用モジュールである","タイマーの作成のみに使うモジュールである"], answer:1, explanation:"datetimeモジュールは日付・時刻を扱うクラスや関数を提供します。datetime.now()で現在日時を取得できます。" },
      { id:"10-5", text:"math.ceil(3.2)の実行結果として正しいものはどれですか？", options:["3","4","3.2","エラーが発生する"], answer:1, explanation:"math.ceil()は引数以上の最小の整数（切り上げ）を返します。3.2を切り上げると4になります。" },
      { id:"10-6", text:"os.listdir('.')の説明として正しいものはどれですか？", options:["現在のディレクトリのパスを返す","現在のディレクトリ内のファイルとディレクトリの名前のリストを返す","ディレクトリを削除する","新しいファイルを作成する"], answer:1, explanation:"os.listdir(path)は指定したパスのディレクトリ内にあるファイルとディレクトリの名前のリストを返します。" },
      { id:"10-7", text:"random.randint(1, 10)の説明として正しいものはどれですか？", options:["1以上10未満のランダムな整数を返す","1以上10以下のランダムな整数を返す","1から10個のランダムな数のリストを返す","0.1から1.0のランダムな浮動小数点数を返す"], answer:1, explanation:"random.randint(a, b)はa以上b以下（両端を含む）のランダムな整数を返します。" },
      { id:"10-8", text:"sys.argvについて正しい説明はどれですか？", options:["Pythonのバージョン情報を格納するリスト","コマンドライン引数を格納するリスト（sys.argv[0]はスクリプト名）","実行中の関数の引数を格納するタプル","システム環境変数の辞書"], answer:1, explanation:"sys.argvはコマンドライン引数のリストです。sys.argv[0]はスクリプト名、sys.argv[1]以降がユーザーが渡した引数になります。" },
      { id:"10-9", text:"math.sqrt(16)の実行結果として正しいものはどれですか？", options:["4","4.0","8","エラーが発生する"], answer:1, explanation:"math.sqrt()は引数の平方根をfloatで返します。math.sqrt(16)は4.0です（整数の4ではありません）。" },
      { id:"10-10", text:"os.path.join()の説明として正しいものはどれですか？", options:["ファイルパスの拡張子を取得する","OSに応じた適切なパス区切り文字でパスを結合する","ファイルが存在するか確認する","ディレクトリを作成する"], answer:1, explanation:"os.path.join()はパスの要素を結合します。OSに応じた区切り文字（Windows:\\, Unix/Mac:/）を自動的に使います。" },
      { id:"10-11", text:"os.path.exists(path)の説明として正しいものはどれですか？", options:["パスのファイルサイズを返す","指定したパスが存在する場合にTrueを返す","パスのファイル名だけを返す","パスを作成する"], answer:1, explanation:"os.path.exists(path)は指定したパス（ファイルまたはディレクトリ）が存在すればTrueを返します。" },
      { id:"10-12", text:"random.shuffle(lst)の説明として正しいものはどれですか？", options:["リストからランダムに1要素を返す","リストを無作為に並び替える（元のリストを変更する）","シャッフルされた新しいリストを返す","リストをソートする"], answer:1, explanation:"random.shuffle()はリストをin-place（元のリストを直接）でシャッフルします。新しいリストは返しません。" },
      { id:"10-13", text:"math.log(100, 10)の実行結果として正しいものはどれですか？", options:["10","2.0","1000","エラーが発生する"], answer:1, explanation:"math.log(x, base)はbaseを底とするxの対数を返します。log10(100) = 2なので2.0が返ります。" },
      { id:"10-14", text:"datetimeモジュールで現在の日時を取得する正しい書き方はどれですか？", options:["datetime.now()","datetime.datetime.now()","datetime.current()","datetime.today.now()"], answer:1, explanation:"datetimeモジュールのdatetimeクラスのnow()メソッドで現在日時を取得します。import datetime後はdatetime.datetime.now()です。" },
      { id:"10-15", text:"math.factorial(5)の実行結果として正しいものはどれですか？", options:["10","15","120","25"], answer:2, explanation:"math.factorial(n)はnの階乗を返します。5! = 5×4×3×2×1 = 120です。" },
    ]
  },
  {
    id: 11, title: "第11章 標準ライブラリめぐり PartII", description: "re・collections・logging", rate: 2.5,
    questions: [
      { id:"11-1", text:"reモジュールの用途として正しいものはどれですか？", options:["ファイルの読み書きを行う","正規表現を使ったパターンマッチングを行う","ネットワーク通信を行う","データベースへのアクセスを行う"], answer:1, explanation:"reモジュールは正規表現（Regular Expression）を扱うモジュールです。re.match()・re.search()・re.findall()などが使えます。" },
      { id:"11-2", text:"collections.Counterの説明として正しいものはどれですか？", options:["数値のカウントダウンを行うクラス","要素の出現頻度を数える辞書のサブクラス","スタックデータ構造を提供するクラス","キューを管理するクラス"], answer:1, explanation:"collections.CounterはイテラブルのHashableな各要素の出現回数を辞書形式で返すクラスです。" },
      { id:"11-3", text:"loggingモジュールを使う利点として正しいものはどれですか？", options:["print()より高速に出力できる","ログレベル・出力先・フォーマットを柔軟に制御できる","自動的にデータベースに保存できる","エラーを自動的に修正できる"], answer:1, explanation:"loggingモジュールはログレベル（DEBUG/INFO/WARNING/ERROR/CRITICAL）の制御、出力先の切り替え、フォーマットの指定など柔軟なログ管理ができます。" },
      { id:"11-4", text:"re.findall('\\\\d+', 'abc123def456')の実行結果として正しいものはどれですか？", options:["['abc', 'def']","['123', '456']","'123'","エラーが発生する"], answer:1, explanation:"re.findall()はパターンにマッチするすべての部分文字列をリストで返します。'\\d+'は1桁以上の連続した数字にマッチします。" },
      { id:"11-5", text:"collections.deque（デック）について正しい説明はどれですか？", options:["要素の重複を許さないコレクション","両端からの追加・削除がO(1)で行えるキュー","キーと値のペアを保持する順序付き辞書","スタックのみに使える固定サイズのコレクション"], answer:1, explanation:"collections.dequeは両端キュー（double-ended queue）です。appendleft()・popleft()で左端へのO(1)操作が可能です。" },
      { id:"11-6", text:"re.sub('a', 'b', 'banana')の実行結果として正しいものはどれですか？", options:["'banana'","'bbnbnb'","'bbanana'","エラーが発生する"], answer:1, explanation:"re.sub(pattern, repl, string)はstringの中のpatternにマッチした部分をすべてreplに置換します。'banana'の'a'をすべて'b'に置換すると'bbnbnb'になります。'bbanana'は最初の'a'だけを置換した場合の誤りです。" },
      { id:"11-7", text:"collections.defaultdictの説明として正しいものはどれですか？", options:["存在しないキーにアクセスするとKeyErrorが発生する辞書","存在しないキーにアクセスするとデフォルト値を自動生成する辞書","キーを自動的にソートする辞書","重複するキーを許容する辞書"], answer:1, explanation:"collections.defaultdictは存在しないキーへのアクセス時に、指定したファクトリ関数でデフォルト値を自動生成します。" },
      { id:"11-8", text:"re.match()とre.search()の違いとして正しいものはどれですか？", options:["match()は文字列の先頭のみ検索し、search()は文字列全体を検索する","search()は文字列の先頭のみ検索し、match()は全体を検索する","両方とも同じ動作をする","match()はリストを返し、search()はマッチオブジェクトを返す"], answer:0, explanation:"re.match()は文字列の先頭でのみパターンマッチングを行います。re.search()は文字列全体を検索して最初のマッチを返します。" },
    ]
  },
  {
    id: 12, title: "第12章 仮想環境とパッケージ", description: "venv・pip の使い方", rate: 2.5,
    questions: [
      { id:"12-1", text:"Pythonで「myenv」という名前の仮想環境を作成するコマンドはどれですか？", options:["python -m venv myenv","python create venv myenv","virtualenv create myenv","pip install venv myenv"], answer:0, explanation:"仮想環境の作成には「python -m venv 環境名」を使います。作成後はWindowsでは「myenv\\Scripts\\activate」で有効化します。" },
      { id:"12-2", text:"pipを使ってパッケージをインストールするコマンドはどれですか？", options:["pip get パッケージ名","pip install パッケージ名","pip add パッケージ名","pip download パッケージ名"], answer:1, explanation:"pipはPythonのパッケージ管理ツールです。「pip install パッケージ名」でPyPIからパッケージをインストールできます。" },
      { id:"12-3", text:"現在インストールされているパッケージの一覧を表示するpipコマンドはどれですか？", options:["pip show","pip list","pip packages","pip installed"], answer:1, explanation:"「pip list」で現在の環境にインストールされているパッケージとそのバージョンの一覧を表示できます。" },
      { id:"12-4", text:"仮想環境を使う主な目的として正しいものはどれですか？", options:["コードの実行速度を向上させる","プロジェクトごとに独立したパッケージ環境を管理する","Python本体を自動更新する","コードを自動的にテストする"], answer:1, explanation:"仮想環境（virtual environment）を使うと、プロジェクトごとに独立したパッケージ環境を作れます。依存関係の分離が可能です。" },
      { id:"12-5", text:"requirements.txtの役割として正しい説明はどれですか？", options:["Pythonのソースコードを保存するファイル","プロジェクトで必要なパッケージとバージョンを記録するファイル","pipの設定ファイル","仮想環境の設定を保存するファイル"], answer:1, explanation:"requirements.txtにはプロジェクトで使用するパッケージ名とバージョンを記述します。「pip install -r requirements.txt」で再現できます。" },
      { id:"12-6", text:"現在の環境のパッケージ一覧をrequirements.txtとして出力するコマンドはどれですか？", options:["pip list > requirements.txt","pip freeze > requirements.txt","pip save requirements.txt","pip export requirements.txt"], answer:1, explanation:"「pip freeze > requirements.txt」で現在インストールされているパッケージとバージョンをrequirements.txt形式で出力できます。" },
      { id:"12-7", text:"インストール済みパッケージをアップグレードするpipコマンドはどれですか？", options:["pip upgrade パッケージ名","pip install --upgrade パッケージ名","pip update パッケージ名","pip refresh パッケージ名"], answer:1, explanation:"パッケージのアップグレードには「pip install --upgrade パッケージ名」を使います。" },
      { id:"12-8", text:"パッケージをアンインストールするpipコマンドはどれですか？", options:["pip delete パッケージ名","pip remove パッケージ名","pip uninstall パッケージ名","pip purge パッケージ名"], answer:2, explanation:"「pip uninstall パッケージ名」でパッケージをアンインストールできます。確認プロンプトが表示されます。" },
    ]
  },
  {
    id: 14, title: "第14章 対話環境での入力行編集とヒストリ置換", description: "対話環境の操作・補完機能", rate: 2.5,
    questions: [
      { id:"14-1", text:"Pythonの対話環境で、以前に入力したコマンドを呼び出す一般的なキー操作はどれですか？", options:["Ctrl+C","上矢印キー（↑）","Ctrl+Z","Esc"], answer:1, explanation:"対話環境では上矢印キー（↑）でヒストリ（過去のコマンド履歴）を遡ることができます。" },
      { id:"14-2", text:"Pythonの対話環境でTabキーを押した場合の動作として正しいものはどれですか？", options:["コードが実行される","インデントが追加される","入力中の名前の補完候補が表示される","対話環境が終了する"], answer:2, explanation:"対話環境ではTabキーで入力補完（コード補完）が行えます。変数名・関数名・メソッド名などの候補が表示されます。" },
      { id:"14-3", text:"対話モードでCtrl+D（WindowsではCtrl+Z）を押した場合の動作として正しいものはどれですか？", options:["現在のコードが実行される","EOF（ファイル終端）シグナルが送られ対話モードが終了する","コマンド履歴が表示される","コードが保存される"], answer:1, explanation:"Ctrl+D（Unix/Mac）またはCtrl+Z（Windows）はEOFシグナルを送り、対話モードを終了させます。" },
      { id:"14-4", text:"readlineモジュールが提供する機能として正しいものはどれですか？", options:["ファイルを1行ずつ読み込む機能","コマンドライン入力の編集とヒストリ機能","ネットワーク通信を行う機能","正規表現によるパターンマッチング機能"], answer:1, explanation:"readlineモジュールはGNU Readlineライブラリを利用した行編集・ヒストリ機能を提供します。" },
      { id:"14-5", text:"対話環境で直前の式の評価結果が自動的に代入される特殊変数はどれですか？", options:["_result","_","__ans__","ans"], answer:1, explanation:"対話環境では直前に評価された式の値が特殊変数「_」（アンダースコア）に自動的に代入されます。" },
      { id:"14-6", text:"対話モードでCtrl+Cを押した場合の動作として正しいものはどれですか？", options:["対話モードが終了する","実行中のコードを中断し、KeyboardInterruptを発生させる","入力内容をコピーする","ファイルを保存する"], answer:1, explanation:"Ctrl+CはKeyboardInterruptを発生させて、実行中の処理を中断します。対話モード自体は終了しません。" },
    ]
  }
];
